config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.Product.urls", namespace='Product')),
    path("Blog/", include("main.Blog.urls", namespace='Blog')),
    path("users/", include("main.users.urls", namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/Product/urls.py
from django.urls import path
from main.Product.apps import ProductConfig
from main.Product.views import contact, ProductListView, ProductUpdateView, ProductCreateView, \
    ProductDetailView, ProductDeleteView, product, catalog


app_name = ProductConfig.name

urlpatterns = [
    path('', product, name='list'), #ProductListView
    path("contact/", contact, name='contact'),
    path("catalog/<int:pk>", catalog, name='catalog'), #ProductDetailView
    path("create/", ProductCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ProductDeleteView.as_view(), name="delete"),
]

main/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView
from django.urls import path

from main.users import views
from main.users.views import send_verification_email, verify
from main.users.apps import UsersConfig
from main.users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('send_verification_email/', send_verification_email, name='send_verification_email'),
    path('verify/', verify, name='verify'),
]

main/Product/models.py
from django.db import models
# Create your models here.
from django.db import models
from django.urls import reverse

from main import users

NULLABLE = {"blank": True, "null": True}
ABLE = {"blank": False, "null": False}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(max_length=100, verbose_name="Описание", **NULLABLE)


    def __str__(self):
        return f"{self.name} {self.description}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Products(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название", unique=True) # unique - уникальность
    description = models.TextField(max_length=100, verbose_name="Описание", **NULLABLE)
    image = models.ImageField(upload_to='media/', verbose_name="Фото", **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    purchase_price = models.IntegerField(default=0, verbose_name="Цена за покупку")
    date_of_creation = models.DateField(default='2023-06-20', verbose_name="Дата создания")
    last_modified_date = models.DateField(default='2023-06-20', verbose_name="Дата последнего изменения")
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.name} {self.description} {self.image} {self.category} " \
               f"{self.purchase_price} {self.date_of_creation} {self.last_modified_date}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Version(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50)
    version_name = models.CharField(max_length=100)  # версия продукта
    is_current = models.BooleanField(default=False)

    def __str__(self):
        return self.version_name


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(verbose_name="описание")

    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name="продукты")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "предмет"
        verbose_name_plural = "предметы"

main/Product/forms.py
from django import forms

from main.Product.models import Products, Subject


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():  # стилизация (нужно в каждый класс)
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Products
        fields = ('id', 'name', 'category', 'image')

    def clean_name(self):
        name = self.cleaned_data["name"]
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError("Название продукта содержит запрещенное слово.")

        return name


class SubjectForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Subject
        fields = "__all__"

main/Product/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from main.Product.forms import ProductForm, SubjectForm
from main.Product.models import Products, Subject

from django.shortcuts import render, redirect

from main.users.models import UserVerification


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Products
    form_class = ProductForm
    success_url = reverse_lazy("Product:create")  # ПЕРЕХОД НА НУЖНУЮ СТРАНИЦУ
    permission_required = "main.Product.add_product"

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin,  UpdateView):
    model = Products
    fields = ("name", "image", "category")
    permission_required = "main.Product.change_product"
    #success_url = reverse_lazy('Blog:list')

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     self.object.owner != self.request.user:
    #     raise Http404
    #     return self.object
    #
    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)   # СОХРАНЕНИЕ

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("Product:update", args=[self.kwargs.get('pk')])  # ПРИВЯЗКА ПО ПК

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Products, Subject, form=SubjectForm, extra=1)
        if self.request.method == "POST":  # пост и гет запрос
            context_data["formset"] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():  # проверка на валидность возвращение и сохранение
            formset.instance = self.object
            formset.save()

            return super().form_valid(form)

class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Products
    template_name = "Product/products_detail.html"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()    # количество просмотров
        return self.object


class ProductDeleteView(UserPassesTestMixin, DeleteView, LoginRequiredMixin):
    model = Products
    success_url = reverse_lazy("Product:list")

    def test_func(self):
        return self.request.user.is_superuser


# @permission_required('main.Product.change_product')
# @login_required  # уровень доступа к стр
def product(request):
    product_list = Products.objects.all()
    for product in product_list:
        active_version = product.version_set.filter(is_current=True).first()
        product.active_version = active_version  # вывод активной версии
    context = {
        'product': product_list,
        "title": "Главная",
    }
    return render(request, "Product/products_list.html", context)

class ProductListView(LoginRequiredMixin, ListView):
    model = Products
    template_name = "Product/products_list.html"
    permission_required = "Product.view_product"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

# @login_required  # уровень доступа к стр
def catalog(request, pk):
    context = {
        'product': Products.objects.filter(id=pk),
        "title": "Главная",
    }
    return render(request, "Product/products_detail.html", context)


# @login_required  # уровень доступа к стр
def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        massage = request.POST.get("massage")
        print(f"{name}\n{email}\n{massage}")
    context = {
        "title": "Контакты",
    }
    return render(request, "Product/contact.html", context)

main/Product/templates/Product/include/inc_main_manu.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap"></use>
        </svg>
    </a>
    <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
        <li>
            <a href="{% url 'Blog:list' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                    <use xlink:href="#table"></use>
                </svg>
                Блог
            </a>
        </li>
        <li>
            <a href="{% url 'Product:list' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                    <use xlink:href="#grid"></use>
                </svg>
                Продукты
            </a>
        </li>
        <li>
            <a href="{% url 'Product:contact' %}" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                    <use xlink:href="#people-circle"></use>
                </svg>
                Контакты
            </a>
        </li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'users:logout' %}" class="nav-link text-white">
                    <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                        <use xlink:href="#grid"></use>
                    </svg>
                    Выйти
                </a>
            </li>
            <li>
                <a href="{% url 'users:profile' %}" class="nav-link text-white">
                    <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                        <use xlink:href="#grid"></use>
                    </svg>
                    Профиль
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% url 'users:login' %}" class="nav-link text-white">
                    <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                        <use xlink:href="#grid"></use>
                    </svg>
                    Войти
                </a>
            </li>
            <li>
            </li>
            <li>
                <a href="{% url 'users:register' %}" class="nav-link text-white">
                    <svg class="bi d-block mx-auto mb-1" width="24" height="24">
                        <use xlink:href="#grid"></use>
                    </svg>
                    Регистрация
                </a>
            </li>
        {% endif %}

    </ul>
</div>

main/Product/templates/Product/include/product_detail.html
{% extends 'Product/base.html' %}

{% block content %}
  <h1>{{ product.name }}</h1>
  <p>{{ product.description }}</p>
  <p>Цена: {{ product.price }} руб.</p>
{% endblock %}