config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.Product.urls", namespace='Product')),
    path("Blog/", include("main.Blog.urls", namespace='Blog')),
    path("users/", include("main.users.urls", namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/Product/urls.py
from django.urls import path
from main.Product.apps import ProductConfig
from main.Product.views import contact, ProductListView, ProductUpdateView, ProductCreateView, \
    ProductDetailView, ProductDeleteView, product, catalog


app_name = ProductConfig.name

urlpatterns = [
    path('', product, name='list'), #ProductListView
    path("contact/", contact, name='contact'),
    path("catalog/<int:pk>", catalog, name='catalog'), #ProductDetailView
    path("create/", ProductCreateView.as_view(), name="create"),
    path("edit/<int:pk>/", ProductUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", ProductDeleteView.as_view(), name="delete"),
]

main/Product/models.py
from django.db import models
# Create your models here.
from django.db import models
from django.urls import reverse

from main import users

NULLABLE = {"blank": True, "null": True}
ABLE = {"blank": False, "null": False}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    description = models.TextField(max_length=100, verbose_name="Описание", **NULLABLE)


    def __str__(self):
        return f"{self.name} {self.description}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Products(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название", unique=True) # unique - уникальность
    description = models.TextField(max_length=100, verbose_name="Описание", **NULLABLE)
    image = models.ImageField(upload_to='media/', verbose_name="Фото", **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    purchase_price = models.IntegerField(default=0, verbose_name="Цена за покупку")
    date_of_creation = models.DateField(default='2023-06-20', verbose_name="Дата создания")
    last_modified_date = models.DateField(default='2023-06-20', verbose_name="Дата последнего изменения")
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    def __str__(self):
        return f"{self.name} {self.description} {self.image} {self.category} " \
               f"{self.purchase_price} {self.date_of_creation} {self.last_modified_date}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Version(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50)
    version_name = models.CharField(max_length=100)  # версия продукта
    is_current = models.BooleanField(default=False)

    def __str__(self):
        return self.version_name


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    description = models.TextField(verbose_name="описание")

    product = models.ForeignKey(Products, on_delete=models.CASCADE, verbose_name="продукты")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "предмет"
        verbose_name_plural = "предметы"

main/Product/forms.py
from django import forms

from main.Product.models import Products, Subject


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():  # стилизация (нужно в каждый класс)
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Products
        fields = ('id', 'name', 'category', 'image')

    def clean_name(self):
        name = self.cleaned_data["name"]
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in forbidden_words:
            if word in name.lower():
                raise forms.ValidationError("Название продукта содержит запрещенное слово.")

        return name


class SubjectForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Subject
        fields = "__all__"

main/Product/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from main.Product.forms import ProductForm, SubjectForm
from main.Product.models import Products, Subject

from django.shortcuts import render, redirect

from main.users.models import UserVerification


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Products
    form_class = ProductForm
    success_url = reverse_lazy("Product:create")  # ПЕРЕХОД НА НУЖНУЮ СТРАНИЦУ
    permission_required = "main.Product.add_product"

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin,  UpdateView):
    model = Products
    fields = ("name", "image", "category")
    permission_required = "main.Product.change_product"
    #success_url = reverse_lazy('Blog:list')

    # def get_object(self, queryset=None):
    #     self.object = super().get_object(queryset)
    #     self.object.owner != self.request.user:
    #     raise Http404
    #     return self.object
    #
    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.name)   # СОХРАНЕНИЕ

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("Product:update", args=[self.kwargs.get('pk')])  # ПРИВЯЗКА ПО ПК

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Products, Subject, form=SubjectForm, extra=1)
        if self.request.method == "POST":  # пост и гет запрос
            context_data["formset"] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():  # проверка на валидность возвращение и сохранение
            formset.instance = self.object
            formset.save()

            return super().form_valid(form)

class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Products
    template_name = "Product/products_detail.html"

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()    # количество просмотров
        return self.object


class ProductDeleteView(UserPassesTestMixin, DeleteView, LoginRequiredMixin):
    model = Products
    success_url = reverse_lazy("Product:list")

    def test_func(self):
        return self.request.user.is_superuser


# @permission_required('main.Product.change_product')
# @login_required  # уровень доступа к стр
def product(request):
    product_list = Products.objects.all()
    for product in product_list:
        active_version = product.version_set.filter(is_current=True).first()
        product.active_version = active_version  # вывод активной версии
    context = {
        'product': product_list,
        "title": "Главная",
    }
    return render(request, "Product/products_list.html", context)

class ProductListView(LoginRequiredMixin, ListView):
    model = Products
    template_name = "Product/products_list.html"
    permission_required = "Product.view_product"

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset

# @login_required  # уровень доступа к стр
def catalog(request, pk):
    context = {
        'product': Products.objects.filter(id=pk),
        "title": "Главная",
    }
    return render(request, "Product/products_detail.html", context)


# @login_required  # уровень доступа к стр
def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        massage = request.POST.get("massage")
        print(f"{name}\n{email}\n{massage}")
    context = {
        "title": "Контакты",
    }
    return render(request, "Product/contact.html", context)

main/Product/templates/Product/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{{ title|title }}</title>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static '/css/album.css' %}" rel="stylesheet">

</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">

                </div>
                {% include "Product/include/inc_main_manu.html" %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-bag-heart-fill" viewBox="0 0 16 16">
                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09zM4.157 8.5H7a.5.5 0 0 1 .478.647L6.11 13.59l5.732-6.09H9a.5.5 0 0 1-.478-.647L9.89 2.41 4.157 8.5z"/>
                </svg>
                <strong>First.pay</strong>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-bag-heart-fill" viewBox="0 0 16 16">
                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09zM4.157 8.5H7a.5.5 0 0 1 .478.647L6.11 13.59l5.732-6.09H9a.5.5 0 0 1-.478-.647L9.89 2.41 4.157 8.5z"/>
                </svg>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">

    <div class="container">
        <p class="float-right">
            <a href="{% url 'Product:contact' %}">Напиши нам</a>
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/Product/templates/Product/contact.html
{% extends "Product/base.html" %}
{% block content %}
    <div class="row align-items-center g-lg-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 text-body-emphasis mb-3">Для связи с нами пишите нам на почту</h1>
            <p class="col-lg-10 fs-4">У нас есть офисы в городах:</p>
            <p class="col-lg-10 fs-4">
                Воронеж,<br>
                Россошь,<br>
                Москва,<br>
                Санкт-Петербург</p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
            <form class="p-4 p-md-5 border rounded-3 bg-body-tertiary" method="post">
                {% csrf_token %}
                <input class="form-control mb-2" name="name" placeholder="Андрей"/>
                <input class="form-control mb-2" name="email" placeholder="Andry2007@example.com"/>
                <textarea class="form-control mb-2" name="massage" placeholder="Хочу с вами работать"></textarea>
                <button type="submit" class="btn btn-outline-primary form-control">Отправить</button>


            </form>
        </div>
{% endblock %}

main/Product/templates/Product/products_confirm_delete.html
{% extends "Product/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href='{% url 'Product:list'%}' class="btn btn-warning">Отменить </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/Product/templates/Product/products_detail.html
{% extends 'Product/base.html' %}
{% block content %}
    <div class="col-10">
    {% for product in product %}
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ product.name|title }}</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ product.purchase_price }}<small class="text-body-secondary fw-light">/руб</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    Категория: {{ product.category|title }}<br>
                    Дата создания: {{ product.date_of_creation|title }}<br>
                    Дата последнего изменения: {{ product.last_modified_date|title }}
                </ul>
                <button type="button" class="w-100 btn btn-lg btn-outline-primary">Купить</button>
            </div>
        </div>
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
    {% endfor %}
{% endblock %}

main/Product/templates/Product/products_form.html
{% extends "Product/base.html" %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype=multipart/form-data>

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Добавить продукт
                    </h3>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-primary">Создать</button>

                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Предмет продукта
                    </h3>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last %}
                            <hr>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer"></div>
            </div>
    </form>
</div>
{% endblock %}

main/Product/templates/Product/products_list.html
{% extends 'Product/base.html' %}
{% block content %}
    <div class="col-12 mb-5">

{#        {% if perms.Product.add_product %}#}
            <a class="btn btn-outline-primary" href="{% url "Product:create" %}">Добавить продукт</a>
{#        {% endif %}#}

    </div>
    {% for object in product %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% load mediapath %}
                    <center/>
                    <div class="card card-cover h-50 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                         style="background-color: #d4edda4;">
                        <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                            <h3 class="card-text"> {{ object.name|title|truncatechars:100 }} </h3>
                            <ul class="d-flex list-unstyled mt-auto">
                                <li class="me-auto">
                                    <img src="{% mediapath object.image %}" width="100%" height="170" alt="Иллюстрация"
                                         class="rounded-circle border border-white">
                                </li>
                        </div>
                        <div class="button_two">
                            <button class="badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill">
                                <a href="{% url 'Product:catalog' object.pk %}" class="text-black">Информация</a>
                            </button>
                            <button class="badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill">
                                <a href="{% url 'Product:contact' %}" class="text-black">Заказать</a></button>

{#                            {% if perms.Product.change_product %}#}
                                <button class="badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill">
                                    <a href="{% url 'Product:update' object.pk %}" class="text-black">Изменить</a>
                                </button>
{#                            {% endif %}#}

{#                            {% if user.is_superuser %}#}
                                <button class="badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill">
                                    <a href="{% url 'Product:delete' object.pk %}"
                                       class="btn-outline-danger">Удалить</a>
                                </button>
{#                            {% endif %}#}

                        </div>
                    </div>
                    {% if perms.Product.version %}
                        <h2>{{ product.name }}</h2>
                        {% if product.active_version %}
                            <p>Активная версия: {{ product.active_version.version_name }}</p>
                        {% else %}
                            <p>Нет активной версии</p>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}