config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.Product.urls", namespace='Product')),
    path("Blog/", include("main.Blog.urls", namespace='Blog')),
    path("users/", include("main.users.urls", namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/Blog/urls.py
from django.urls import path

from main.Blog.apps import BlogConfig
from main.Blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name='create'),
    path("", BlogListView.as_view(), name='list'),
    path("view/<int:pk>", BlogDetailView.as_view(), name='view'),
    path("edit/<int:pk>", BlogUpdateView.as_view(), name='edit'),
    path("delete/<int:pk>", BlogDeleteView.as_view(), name='delete'),
]

main/Blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}
ABLE = {"blank": False, "null": False}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name="Название")
    slug = models.CharField(max_length=150, verbose_name="Slug", **NULLABLE)
    body = models.TextField(verbose_name="Содержимое", **NULLABLE)
    preview = models.ImageField(upload_to='media/', verbose_name="Фото", **NULLABLE)
    create_data = models.DateField(default='2023-06-20', verbose_name="Дата создания", **NULLABLE)
    sign_publication = models.CharField(max_length=150, verbose_name="Признак публикации", **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

main/Blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from main.Blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', "body")
    success_url = reverse_lazy('Blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', "body")
    #success_url = reverse_lazy('Blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("Blog:view", args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()    # количество просмотров
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy("Blog:list")

main/Blog/templates/Blog/blog_confirm_delete.html
{% extends "Product/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title|title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href='{% url 'Blog:list'%}' class="btn btn-warning">Отменить </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/Blog/templates/Blog/blog_detail.html
{% extends 'Product/base.html' %}
{% load mediapath %}
{% block content %}

    <div class="card">
        <img src="{% mediapath object.preview %}" width="100%" height="170" alt="Иллюстрация" style="float: left;">

        <div class="card-body">
            <h4 class="card-title">{{ object.title|title|truncatechars:100 }}</h4>
        </div>

        <ul class="list-group list-group-flush">
            <li class="list-group-item">Дата создания : {{ blog.create_data|title }}</li>
            <li class="list-group-item">Просмотров : {{ object.views_count }}</li>
            <li class="list-group-item">Cсылка : {{ object.slug }}</li>
        </ul>
    </div>
    <table class="table" style="text-align: right;">
        <tr>
            <td>Факты:</td>
            <td>{{ blog.body|title }}</td>
        </tr>
    </table>
{% endblock %}

main/Blog/templates/Blog/blog_form.html
{% extends "Product/base.html" %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/Blog/templates/Blog/blog_list.html
{% extends 'Product/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url "Blog:create" %}">Добавить блог</a>
    </div>
    {% for object in blog_list %}
        {% load mediapath %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {% load mediapath %}
                    <center/>
                    <div class="card card-cover h-50 overflow-hidden text-bg-dark rounded-4 shadow-lg"
                         style="background-color: #dae0e5">
                        <div class="d-flex flex-column h-100 p-5 pb-3 text-shadow-1">
                            <h3 class="card-text"> {{ object.name|title|truncatechars:100 }}
                            {{ object|title }}</h3>
                            <ul class="d-flex list-unstyled mt-auto">
                                <li class="me-auto">
                                    <img src="{% mediapath object.preview %}" width="100%" height="170" alt="Иллюстрация"
                                         class="rounded-circle border border-white">
                                </li>
                        </div>
                        <div class="button_two">
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                    href="{% url 'Blog:view' object.pk %}" class="text-black">Информация</a>
                            </button>
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                    href="{% url 'Blog:edit' object.pk %}" class="text-black">Обновить</a>
                            </button>
                            <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                    href="{% url 'Blog:delete' object.pk %}" class="text-black">Удалить</a>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}