config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.Product.urls", namespace='Product')),
    path("Blog/", include("main.Blog.urls", namespace='Blog')),
    path("users/", include("main.users.urls", namespace='users'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView
from django.urls import path

from main.users import views
from main.users.views import send_verification_email, verify
from main.users.apps import UsersConfig
from main.users.views import RegisterView, ProfileView

app_name = UsersConfig.name

urlpatterns = [
    path("", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('send_verification_email/', send_verification_email, name='send_verification_email'),
    path('verify/', verify, name='verify'),
]

main/users/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User

from main.Product.models import NULLABLE, Products


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="почта")
    product = models.ForeignKey(Products, on_delete=models.CASCADE, **NULLABLE)

    avatar = models.ImageField(upload_to="users/", verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name="телефон")
    country = models.CharField(max_length=100, verbose_name='страна', **NULLABLE)


    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

class UserVerification(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    verification_code = models.CharField(max_length=255)
    is_verified = models.BooleanField(default=False)

main/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


from main.users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("email",
                  "first_name",
                  "last_name",
                  "phone",
                  "country",
                  "avatar",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)  # скрывает поле пароля

        self.fields['password'].widget = forms.HiddenInput()


class EmailVerificationForm(forms.Form):
    email = forms.EmailField()

main/users/views.py
import random
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.shortcuts import render, redirect
from main.users.forms import UserRegisterForm, UserProfileForm, EmailVerificationForm
from main.users.models import User, UserVerification


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        print(form.cleaned_data)
        response = super().form_valid(form)
        user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])  # регистрация
        if user is not None:
            login(self.request, user)
        return response


class PasswordResetCustomView(PasswordResetView):
    template_name = 'users/password_reset.html'
    success_url = reverse_lazy('users:password_reset_done')


class  ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


def verify(request):
    if request.method == 'POST':
        verification_code = request.POST.get('verification_code')
        user_verification = UserVerification.objects.get(verification_code=verification_code)
        user_verification.is_verified = True
        user_verification.save()
        return redirect('/')
    else:
        return render(request, 'verification/verify.html')


def send_verification_email(request):
    if request.method == 'POST':
        form = EmailVerificationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.get(email=email)
            verification_code = str(random.randint(100000, 999999))
            UserVerification.objects.create(user=user, verification_code=verification_code)
            send_mail(
                'Verification code',
                f'Ваш код для авторизации {verification_code}',
                'margoonavt@yandex.ru',
                [email],
                fail_silently=False,
            )
            return redirect('users:verify')
    else:
        form = EmailVerificationForm()
    return render(request, 'verification/send_verification_email.html', {'form': form})

main/users/templates/users/login.html
{% extends "Product/base.html" %}
{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype=multipart/form-data>
            <div class="col-6"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <button class="btn btn-outline-info">
                            <a href="{% url "users:password_reset_done" %}" class="text-black">Восстановить пароль</a>
                        </button>

                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

main/users/templates/users/password_reset.html
{% extends "Product/base.html" %}
{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype=multipart/form-data>
            <div class="col-6"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Регистрация</button>
                        <button class="btn btn-outline-info">
                            <a
                                    href="{% url "users:password_reset_done" %}" class="text-black">Восстановить
                                пароль</a>
                        </button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

main/users/templates/users/register.html
{% extends "Product/base.html" %}
{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype=multipart/form-data>
        <div class="col-6"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Регистрация</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

main/users/templates/users/user_form.html
{% extends "Product/base.html" %}
{% block content %}

    <div class="col-12">
        <form class="row" method="post" enctype=multipart/form-data>
            <div class="col-6"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Профиль
                        </h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button class="btn btn-outline-info">
                            <a href="{% url "users:send_verification_email" %}" class="text-black">Подтвердить почту</a>
                        </button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}